apiVersion: apps/v1
kind: Deployment
metadata:
  name: n14724-notes-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n14724-notes-api
  template:
    metadata:
      labels:
        app: n14724-notes-api
    spec:
      imagePullSecrets:
        - name: devops101registry-credentials
      containers:
        - name: notes-api
          image: devops101registry.azurecr.io/n14724-notes-api:v0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: n14724-notes-api
spec:
  type: LoadBalancer
  selector:
    app: n14724-notes-api
  ports:
    - protocol: TCP
      port: 80