---
name: "Tedial Deploy"
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**/main/**'
      - '**README.md'
    branches:
      - stage

env:
  PACKAGE_VERSION: test-version-001
  SOMETHING: something

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3
      - name: puppet-lint
        uses: scottbrenner/puppet-lint-action@master
        with:
          args: ./
  push:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Retrieve version
        run: |
          echo "TAG_NAME=$(git describe --tags --long --abbrev=4)" >> $GITHUB_ENV
      - name: Output version
        run: |
          echo "${{ env.TAG_NAME }}"

      - name: Create artifacts folder
        run: |
          mkdir "$GITHUB_WORKSPACE/artifacts"
      - name: Install Octopus CLI
        uses: OctopusDeploy/install-octopus-cli-action@v1
        with:
          version: latest
      - name: List files in workflow source folder
        run: |
          ls -al source
      - name: Package Puppet config files
        run: |
          octo pack --id="PuppetConfigFiles" --format="Zip" \
          --basePath="$GITHUB_WORKSPACE/source" \
          --outFolder="$GITHUB_WORKSPACE/artifacts"
      - name: List files in workflow artifacts folder
        run: |
          ls -al artifacts
      - name: Push Puppet config files package
        uses: OctopusDeploy/push-package-action@v1
        with:
          api_key: ${{ secrets.OCTOPUSSERVERAPIKEY }}
          server: ${{ secrets.OCTOPUSSERVERURL }}
          packages: "artifacts/OctoPetShop.Database.${{ env.PACKAGE_VERSION }}.zip"
          space: ${{ secrets.OCTOPUSSERVER_SPACE }}
