---
name: "Tedial Deploy"
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**/main/**'
      - '**README.md'
    branches:
      - stage

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3
      - name: puppet-lint
        uses: scottbrenner/puppet-lint-action@master
        with:
          args: ./
