---
name: "Tedial Deploy"
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**/main/**'
      - '**README.md'
    branches:
      - stage

env:
  PACKAGE_VERSION: test-version-001
  SOMETHING: something

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3
      - name: puppet-lint
        uses: scottbrenner/puppet-lint-action@master
        with:
          args: ./
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create artifacts folder
        run: |
          mkdir "$GITHUB_WORKSPACE/artifacts"
      - name: Install Octopus CLI
        uses: OctopusDeploy/install-octopus-cli-action@v1
        with:
          version: latest
      - name: Package Puppet config files
        run: |
          octo pack --id="PuppetConfigFiles" --format="Zip" --version="$PACKAGE_VERSION" \
          --basePath="$GITHUB_WORKSPACE/source" --outFolder="$GITHUB_WORKSPACE/artifacts"
      - name: List files in artifacts folder
        run: |
          ls -al
